"""2_values

Revision ID: 2d2a51ee77c3
Revises: 1ef433423591
Create Date: 2022-05-07 16:56:16.589767

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2d2a51ee77c3'
down_revision = '1ef433423591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value',
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subkey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_key'), 'value', ['key'], unique=False)
    op.create_index(op.f('ix_value_subkey'), 'value', ['subkey'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_value_subkey'), table_name='value')
    op.drop_index(op.f('ix_value_key'), table_name='value')
    op.drop_table('value')
    # ### end Alembic commands ###
