"""3_user_tel

Revision ID: 5e61999f8990
Revises: 2d2a51ee77c3
Create Date: 2022-05-23 12:54:43.177531

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5e61999f8990'
down_revision = '2d2a51ee77c3'
branch_labels = None
depends_on = None


# naming_convention={
#     "ix": "ix_%(column_0_label)s",
#     "uq": "uq_%(table_name)s_%(column_0_name)s",
#     "ck": "ck_%(table_name)s_%(constraint_name)s",
#     "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
#     "pk": "pk_%(table_name)s"
# }
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tel', sa.VARCHAR(), nullable=True))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_user_tel', 'user', ['tel'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_tel', 'user', type_='unique')
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'tel')
    # ### end Alembic commands ###
