"""4_posts_and_files

Revision ID: c2d26ba94c94
Revises: 5e61999f8990
Create Date: 2022-05-23 16:17:45.845923

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c2d26ba94c94'
down_revision = '5e61999f8990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('slug_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('post_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('is_write', sa.Boolean(), nullable=True),
    sa.Column('is_publish', sa.Boolean(), nullable=True),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('file',
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('post')
    # ### end Alembic commands ###
